name: relaxdiego
description: DevOps + Software Engineering + Agile
url: https://www.relaxdiego.com
enforce_ssl: www.relaxdiego.com
permalink: /:year/:month/:title.html
highlighter: rouge
markdown: kramdown
