name: relaxdiego
description: Software Development and other stuff.
url: http://www.relaxdiego.com
permalink: /:year/:month/:title.html
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-asciidoc
